FSRHomepage/config/routes.rb
Rails.application.routes.draw do
  resources :homes

  resources :categories

  resources :links

  resources :teams

  resources :contents

  resources :rolles

  root 'homes#index'

end

FSRHomepage/app/models/rolle.rb
class Rolle < ActiveRecord::Base
  belongs_to :user
end

FSRHomepage/app/controllers/rolles_controller.rb
class RollesController < ApplicationController
  before_action :set_rolle, only: [:show, :edit, :update, :destroy]

  # GET /rolles
  # GET /rolles.json
  def index
    @rolles = Rolle.all
  end

  # GET /rolles/1
  # GET /rolles/1.json
  def show
  end

  # GET /rolles/new
  def new
    @rolle = Rolle.new
  end

  # GET /rolles/1/edit
  def edit
  end

  # POST /rolles
  # POST /rolles.json
  def create
    @rolle = Rolle.new(rolle_params)

    respond_to do |format|
      if @rolle.save
        format.html { redirect_to @rolle, notice: 'Rolle was successfully created.' }
        format.json { render :show, status: :created, location: @rolle }
      else
        format.html { render :new }
        format.json { render json: @rolle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rolles/1
  # PATCH/PUT /rolles/1.json
  def update
    respond_to do |format|
      if @rolle.update(rolle_params)
        format.html { redirect_to @rolle, notice: 'Rolle was successfully updated.' }
        format.json { render :show, status: :ok, location: @rolle }
      else
        format.html { render :edit }
        format.json { render json: @rolle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rolles/1
  # DELETE /rolles/1.json
  def destroy
    @rolle.destroy
    respond_to do |format|
      format.html { redirect_to rolles_url, notice: 'Rolle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rolle
      @rolle = Rolle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rolle_params
      params[:rolle]
    end
end

FSRHomepage/app/helpers/rolles_helper.rb
module RollesHelper
end

FSRHomepage/app/views/rolles/_form.html.erb
<%= form_for(@rolle) do |f| %>
  <% if @rolle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rolle.errors.count, "error") %> prohibited this rolle from being saved:</h2>

      <ul>
      <% @rolle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FSRHomepage/app/views/rolles/edit.html.erb
<h1>Editing rolle</h1>

<%= render 'form' %>

<%= link_to 'Show', @rolle %> |
<%= link_to 'Back', rolles_path %>

FSRHomepage/app/views/rolles/index.html.erb
<h1>Listing rolles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rolles.each do |rolle| %>
      <tr>
        <td><%= link_to 'Show', rolle %></td>
        <td><%= link_to 'Edit', edit_rolle_path(rolle) %></td>
        <td><%= link_to 'Destroy', rolle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rolle', new_rolle_path %>

FSRHomepage/app/views/rolles/new.html.erb
<h1>New rolle</h1>

<%= render 'form' %>

<%= link_to 'Back', rolles_path %>

FSRHomepage/app/views/rolles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_rolle_path(@rolle) %> |
<%= link_to 'Back', rolles_path %>